### ISSUE TITLE
Project One Feedback

### ISSUE THREAD

**Issue by ajhofferber** [brianduggan/simplegameproject#1]
Hey Brian,

Cool project! I really liked how you added comments to each section of your scripts to explain what was going on where. Your code is clean and well-organized! The game works really well and I like the jQuery animations that you have going on.

As it is, it totally meets project requirements and is working really well.  But I know we've talked about things you could potentially add to the game, and I think it would be really cool to add in some kind of betting feature. How do you think you would get into adding something like that?

Again, great work on your project!

-Ash

**Comment by Avizacherman** [comment]
Brian,

Great work with your project. I like the graphical display of cards, your logic is sound and very well organized. I also like that you got those pesky aces to work. Agree with Ash, would have loved to have seen some additional features such as betting or splitting. Also, I had a situation where I tied with the dealer and it didn't push. Overall really well done.

Score: 2/3 (check scoring rubric for more details)

-Avi
